controllers/core-commandrouter.js, controllers/core-musiclibrary.js, controllers/interface-webui.js, public/scripts/volumio/index-socketio-controller.js, views/index.ejs
Changes to these files were in progress when the eslint change took effect. Will run eslint on these in a separate commit.
=> Music Library Updates

.gitmodules, README.md, http/www/.gitignore
I couldn't test this because I don't have access to the Volumio2-UI repo, but I'm fairly sure this should work.
To make this work, you'll need to run this in the UI repo:
```shell
git-subtree split --prefix dist -b dist
git checkout dist
git push origin dist
```
That will automatically create a new branch based on the dist/ directory.
The new branch will be called dist.
Push that branch to GitHub.
When that is done, check out this PR and run
```shell
git submodule init
git submodule update --remote
```
After that you should have the UI's dist folder (technically branch) at http/www.
To update the UI in future, update the dist branch using the subtree command and update the submodule in this repo.
=> Use git submodule for UI

package.json
Issue #62 
Added missing `wireless-tools` to `package.json`.
=> added missing dependency

app/plugins/miscellanea/albumart/albumart.js
In case file size is zero the default albumart is returned
=> zero file size

app/index.js, app/pluginmanager.js
* Plugin not loaded when trying to get an instance (pluginmanager)
* Unknown method on plugin during call (app/index.js)
=> Added some error messages to help developers

app/plugins/music_services/dirble/index.js
see issue #136 
we don't add stations without streams
Caution : this method need better exception processing !
=> Don't add station without streams

app/plugins/system_controllers/networkfs/index.js
can you try this one ? there was a bug when adding a new drive with an empty username
=> Nfs mount (v2)

app/plugins/music_services/airplay_emulation/index.js, app/plugins/music_services/airplay_emulation/package.json, app/plugins/music_services/airplay_emulation/shairport-sync.conf.tmpl
Plugin includes its own template file for shairport, fixed plugin category.
=> fixed plugin category, added tmpl file

app/plugins/system_controllers/networkfs/index.js
=> Rework on size for mounted shares

app/plugins/music_services/dirble/index.js
list of countries and radio stations by country are now sorted alphabetically
(Pagination doesn't work atm...)
=> issue #162 : sort radio stations and countries alphabeticaly

logsubmit.js
=> Fix file collision for logging

app/plugins/audio_interfaces/alsa_controller/index.js, app/plugins/music_services/mpd/index.js
Hi,
here are the first set of optimisation I have done to the MPD service. I have got it currently as fast as it can be with the current way it works. I think it is a bit faster.
I'm a bit tired now, so I'll leave it to you to try out.
Let me know how you get on.
=> MPD service optimisation

.gitignore, app/index.js, app/playqueue.js, app/plugins/user_interfaces/websocket/index.js, app/statemachine.js
Hi,
In this one I tidy up app/index.js
it now uses strict mode, which can help V8 with optimisation and detection of possible bugs.
I have removed a load of unnecessary calls to '.cal(...)' as the scope is not in question in these cases - when you call a method from an object that was created with new() then its scope is a bit more solid.
The statemachine has much simplified promise handling
For example, Instead of
```
return self.updateTrackBlock()
.then(libFast.bind(self.getState, self))        
.then(libFast.bind(self.pushState, self));
```
there is
```
self.updateTrackBlock();
return self.pushState()
```
This has been done by allowing some of the inner workings of the state machine and playqueue to become synchronous.
Other code has been tidied up too.
This should probably all be …
=> Lots of work

app/playlistManager.js, app/plugins/music_services/mpd/index.js
I have made it possible to add a directory of songs to a playlist. In the current release it actually causes Volumio to reboot when you look at some playlists created this way - I do not understand fully, but this new version is better.
It does not yet work for directories inside directories yet, but I will work on that next.
In order to make this work in any sane manner I had to make the fake asynchronous method
`ControllerMpd.prototype.getAlbumArt`
synchronous - I do not know why it was asynchronous, it just returns a string that is calculated internally - was there a reason?
The whole album art setup is very confusing to me, and sometime it doesn't not seem to work, but I think this addition is a good place to start.
BTW we seem to be getting code in these things that only works for …
=> Adding directories to playlist

README.md
https://en.wikipedia.org/wiki/Date_format_by_country, https://en.wikipedia.org/wiki/ISO_8601
I never heard of YYYY-dd-mm before :)
=> Use standard date format

app/plugins/music_services/airplay_emulation/index.js
Hi Volumio
I have managed to get airplay working in Volumio2 without distortion through my DAC's.
All that is necessary is to change 'hw' to 'plughw' for the device definition.
My wife is now happy :-)
Conrad
=> Fixing Airplay distortion

app/plugins/music_services/mpd/index.js
improve albumart quality from 174x174 to 300x300
=> album art quality extralarge (300x300)

app/plugins/music_services/mpd/UIConfig.json, app/plugins/system_controllers/network/UIConfig.json, app/plugins/system_controllers/system/UIConfig.json
-Changed the yes/no dropdowns to switches. Reducing the number or clicks
or touches needed to change the setting.
-Changed the labels for the audio buffer size to something more user
friendly.
=> Playback Options UI Improvements

app/plugins/system_controllers/i2s_dacs/dacs.json
=> Aoide DACs config

app/plugins/system_controllers/i2s_dacs/dacs.json
=> dac alphabetical re-order

app/plugins/music_service/example_plugin/index.js
=> add var libQ = require('kew');

app/i18n/strings_fr.json
=> update french translation

app/i18n/strings_en.json
https://github.com/volumio/Volumio2/issues/248
=> Fixes issue #248

LICENSE.md
Noticed that the website had the license posted, but the repo didn't. Added the matching license to the repo.
=> Added GNU3 license

app/i18n/strings_en.json
Let's hope I did it sucecssfully
=> Fixed an EN typo

package.json
=> chore(package): update shelljs to version 0.7.2

app/i18n/strings_fr.json
=> add plugin fields

app/i18n/strings_fr.json
remove illegal characters that hangs volumio
=> illegal characters correction

app/i18n/strings_sv.json
Added blank space to Swedish translation of "DOWNLOADING_FROM"
=> Added blank space to Swedish translation of "DOWNLOADING_FROM"

app/plugins/music_service/example_plugin/index.js
The comments in the various functions were just plain copy and paste. This brings them in line with the actual purpose of its functions. More details might be needed.
=> Make the comments reflect the purpose of its functions

package.json
=> chore(package): update yargs to version 6.0.0

app/i18n/strings_en.json, app/musiclibrary.js, app/plugins/music_service/last_100/index.js, app/plugins/music_service/last_100/package.json
=> Finalized Last 100 plugin, yeah

app/plugins/user_interface/websocket/index.js
Change property to "name" to be consistent with rest of API and documentation. Updated in UI as well.
=> Consistency in playlist API

app/plugins/music_service/webradio/index.js
Fixes issue https://github.com/volumio/Volumio2/issues/796
=> Sort webradio lists alphabetically

app/plugins/system_controller/i2s_dacs/dacs.json
Add a new dac hat "HiFiBox DAC".
this is a dac hat for raspberry pi 0\1\2\3. The product photo is here http://wangxianyuan.com/wp-content/uploads/2016/11/hifiboxdac-blogpost.png
=> Updata dacs.json, Add a new dac hat "HiFiBox DAC"

app/plugins/system_controller/network/index.js
Sorry, my bad (wrong cut&paste)
=> Fix typo in commit #3a09b4b

app/plugins/system_controller/system/index.js, app/plugins/user_interface/websocket/index.js
The method will ask Volumio to give its name and its uuid. Data is retrieved from shared variables and returned in a JSON object
=> Adding getDeviceInfo to retrieve device name and uuid

app/plugins/user_interface/mpdemulation/helper.js, app/plugins/user_interface/mpdemulation/index.js
- fixed missing 'this/'/'self' reference by explicitly calling handleMessage
- 'play' now toggles between 'play' and 'pause'
('mpc toggle' requests the current status, which seems to work, but still calls 'play' even when the state already is 'play', so this is a workaround)
- tried implementing mpd command lists, mpc sends all commands in the list but still returns an error message at the end
- implemented 'volume' (incrementally change volume)
I'm not a regular javascript developer. My implementation not exactly flawless, but it works.
Confirmed working commands:
- 'mpc -p 6500 -q play'
- 'mpc -p 6500 -q pause'
- 'mpc -p 6500 -q prev'
- 'mpc -p 6500 -q next'
- 'mpc -p 6500 -q volume +[num]' (or -[num], only works with incremental volume changes as setvol isn't implemented)
=> implemented basic mpdemulation commands

app/plugins/music_service/mpd/index.js
See: https://github.com/volumio/Volumio2/issues/969
=> Album name is now URL encoded in listAlbums from MPD Controller

app/plugins/music_service/mpd/index.js
it's the first time I am working with github D: so I hope I am doing this right.
=> group album list by albumartist instead of artist

app/plugins/system_controller/networkfs/index.js
Quote the NAS mountpoint when calling 'df' and return just the wanted value
with no units, so computing a displayed size becomes simpler.
Fixes: #856
=> Make retrieval of share size a little more robust.

app/plugins/system_controller/networkfs/index.js
Fixes #1022. Tested on 2.041+ all the recently merged PRs for the networkfs plugin.
=> Addshare fixes

app/plugins/system_controller/networkfs/index.js
I started looking into #627 and noticed that some shares were not being detected properly by discoverShares(). I've fixed that and hopefully improved the readability somewhat. This has been tested on 2.041 and seems to work correctly.
=> Improve discoverShares()

app/plugins/music_service/mpd/index.js
=> Avoid  crash if a file in the music db is not available

app/plugins/system_controller/networkfs/index.js
Apologies - I did not check the uuid already defined case...
=> Bugfix for addShare

app/index.js, app/playlistManager.js, app/playqueue.js, app/plugins/music_service/mpd/index.js, app/plugins/user_interface/websocket/index.js, app/statemachine.js
=> Revert "Favourties fix"

app/index.js, app/playlistManager.js, app/playqueue.js, app/plugins/music_service/mpd/index.js, app/plugins/user_interface/websocket/index.js, app/statemachine.js
=> Revert "Revert "Favourties fix""

app/plugins/miscellanea/albumart/albumart.js
Fix Artist artwork and remove redundant code
=> Fix Artist artwork

app/plugins/music_service/mpd/index.js
=> Fix Search Function

app/index.js
Add extra verification of pushState and pushQueue method on plugin #1070
=> Add defensive for volumioPushState and volumioPushQueue method

app/plugins/system_controller/volumiodiscovery/package.json
=> Minor typo

app/i18n/strings_en.json, app/plugins/music_service/mpd/index.js
Added 3 variables at start of file;
var tracknumbers = true/false - If set to 'true' then track numbers are
added to song titles.
var compilation = ['Various', 'VA', 'Various Artists'etc...] -
Identifies different strings which are used as AlbumArtist for
compilation Albums.
var artistsort = true/false - List artists by albumartist if set to true
or artist if set to false.
Fixed search to find albums which have duplicated names (Greatest Hits
etc...).
Added count of matches in search results.
Fixed adding album to Queue or Playlist which has name that is
duplicated (previously it added tracks from all albums with duplicate
name)
Fixed browsing by Genre to allow 'drilling down' correctly.
Probably a few other fixes I've forgotten......
=> Various fixes and enhancements for mpd/index.js

app/i18n/strings_en.json, app/playlistManager.js, app/plugins/music_service/mpd/index.js
Add function listallFolder to mpd/index.js to list all songs from a
folder including sub-folders.
Include call to listallFolder function and additional code in
playlistManager.js
=> Fix Issue #1182

app/plugins/miscellanea/alarm-clock/index.js
Reported as #1240. Tested on 2.201 with timeouts of minutes only, hours & minutes, for both the 'stop music' and 'power off' cases.
=> Avoid NaN in toast popup after setting a sleep

app/plugins/music_service/mpd/index.js
Replaced nodetools.en/decodeURL with en/decodeURIComponent to encode URL allowed characters ( /?:@&=+$# ) - fixes issue with artist names such as AC/DC
Added codedArtistName to listAlbums function as this was missing
see [https://volumio.org/forum/album-view-not-converting-characters-t6989.html](url) for more info
=> Fix special characters in artist name

README.md
=> Add "via ssh" to "no root login"

app/plugins/system_controller/i2s_dacs/index.js, app/plugins/system_controller/network/index.js, app/plugins/system_controller/system/index.js, logsubmit.js
I know it's trivial but couldn't keep looking at it...
=> Fix spelling of 'Cannot'

app/plugins/audio_interface/alsa_controller/index.js
This fix is related to the issues #1168 and #1239 and to my former pull request #1288.
The fix is successfully tested by me and some other users reporting the problem (see #1168).
If I can support in additional regression testing, just give me a hint.
=> Softvolume bugfix - issues #1168 & #1239

app/platformSpecific.js
More conventional and more future-proof (i.e: debian-stretch)
=> Do shutdown/reboot the systemd way

app/plugins/music_service/mpd/index.js
as discussed in Bluetooth PR [ ](https://github.com/volumio/Volumio2/pull/1317)
for usage see: (https://github.com/geeks-r-us/volumio-plugins/tree/f/bluetooth/plugins/audio_interface/bluetooth_controller)
=> added callback mechanism which allows adding lines to mpd.conf

README.md
https://github.com/thibmaek/awesome-raspberry-pi is the correct repo
=> fix url to correct github awesome-raspberry-pi list

app/plugins/system_controller/volumio_command_line_client/commands/pull.sh, app/plugins/system_controller/volumio_command_line_client/volumio.sh
By chance I ran 'volumio pull' from a shell sitting in /volumio. The result wasn't pretty.
This series should reduce the chances of things going wrong.
=> Small improvements to 'volumio pull'

app/i18n/strings_nl.json
gedeaktiveerd ==> gedeaCtiveerd
=> small spelling mistake

app/i18n/strings_de.json, app/i18n/strings_en.json, app/i18n/strings_fr.json, app/i18n/strings_it.json
=> Make advice about password length consistent at 8+ characters.

app/index.js
As wished in #1357 I have created a new PR containing only the changes needed for adding localization support.
=> implemented localization support for plugins

app/plugins/audio_interface/alsa_controller/cards.json
Added support for Cheapo card for Sparky
=> Support for Cheapo card for Sparky.

app/plugins/music_service/mpd/index.js, app/plugins/music_service/upnp_browser/index.js, app/plugins/music_service/webradio/index.js
This replaces PR #1455. See also Issues #1454 and #1430
=> Properly escape double quotes when constructing mpd command strings - respin

app/playlistManager.js, app/statemachine.js
A small bit of work around favourites:
Fix the state not being refreshed when you un-favourite a track on the playback screen
Resolve an unresolved promise in statemachine.checkFavourites
=> Favourites

app/volumecontrol.js
The promise was not propagated properly, this should work again now.
Plus updated some comments, minor grammatical changes.
fixes #1560
=> Fixed the volume toggle function

app/plugins/music_service/upnp_browser/index.js, package.json
I had difficulties to get your project running, therefor I have not been able to actually test the changes I made. Please consider these proposed changes as a some guidance how to do the update.
Related issue: #1593.
=> Update to music-metadata

crashreport.js, index.js, logsubmit.js, package.json, update-helper.js, wsclient.js
Further to #1612 
First install the dependencies with `npm install --only=dev` or more specifically:
```shell
> npm i husky@next lint-staged prettier semistandard
```
All further commits will be automatically formatted using the `semistandard` style  and will prompt you to adhere to the styleguide. 
We could then fix all lint errors in the file when you make some changes, rather than attempt to fix the entire repo in one go.  
Of course you can always pass the `--no-verify` flag to git if you don't feel inclined to fix all the lint errors, and just use the formatting.  
Also included sample of the formatting for the parent dir. I started fixing all the lint errors, but soon got bored. :-}
If this works, can run the formatting for the entire repo in oneshot.
=> Set up consistant codestyle

app/plugins/system_controller/networkfs/index.js
Since the mounting of NAS drives is done as root, we need to take
some care with quoting the strings supplied by the user for things
like username, password, mount options, etc. As long as the strings
are single-quoted, the shell used for calling 'mount' should never
try to interpret the characters in between. Things get trickier when
the input shell contains a single quote. Then we have to turn any
single ' within the string into the sequence '"'"'.
=> Improve quoting of user input to mountShare

app/plugins/system_controller/system/index.js
I have allowed Tinkerboard to use Install To Disk for testing transfer to internal eMMC.
Perhaps the device limitation could be lifted in the future, it is a convenient way to copy/clone a running instance to internal disks. HDD or eMMC/SD makes no difference with the new version.
Relocating the backup GPT table has been removed as it was X86-specific and has been solved in a different way.
Once initrd for arm devices have been aligned with x86 regarding initial resize handling, the creation of the resize-datapart sentinel file can also be removed from Install To Disk.
=> Install To Disk: added use of eMMC/SD disks

app/plugins/system_controller/volumio_command_line_client/volumio.sh
For play/pause and 'volume toggle' (mute/unmute)
Addresses #1697
=> Documenting 'toggle'

app/plugins/music_service/upnp_browser/index.js
This is a suggested fix for #1724
=> Deal with devices without a serviceList #1724

app/plugins/music_service/mpd/index.js
Fix certain albums not playing
Fix the regression when attempting to play the album adds all tracks among albums of the same name to be added to the queue.
=> Fix certain albums not playing and regression.

app/i18n/strings_nl.json
Fixed translation of LAST_100, first letter was not capitalized.
=> Update strings_nl.json, fix missing capitalization.

app/plugins/music_service/mpd/index.js
Include the tracknumber of the current track in the return value so it can be provided by the API and WebSocket interfaces
=> tracknumbers in albums view

app/plugins/music_service/mpd/index.js
Fix albums not playing (put on queue) after a search because the TAG albumartist is empty.
(bug report : https://forum.volumio.org/problem-playing-certain-albums-volumio-599-and-598-t12774.html)
=> Fix certain albums not playing after a Search

app/playlistManager.js
Fixes: #1716
Tested on rpi2 and release 2.526.
=> Correct handling of artists:// uri with an album appended

app/plugins/miscellanea/albumart/albumart.js
untested...
apologies for the silly concatenation error (too much perl in my fingers)
=> magic number phobia

app/i18n/strings_en.json, app/plugins/music_service/webradio/index.js
Tested by loading into 2.692 and restarting, no crashing etc was observed.
No idea how to force it to return an error, to exercise the changed lines.
=> Localise error messages

app/plugins/audio_interface/alsa_controller/index.js
=> Revert "Refactor and simplify `getAplayInfo` to be more robust"

app/plugins/music_service/webradio/index.js
- allow search for radio with several space in name "france bleu pays de savoie"
- allow search for radio with accented character in name "france bleu isère" using https://www.unicode.org/reports/tr15/
=> WebRadio Update index.js to allow multiple space and accented characters in radio name

app/plugins/music_service/webradio/index.js
With this PR, Radio stations are sorted in alphabetical order.
before result : 
after PR :
=> Webradio : sorting the result in alphabetical oreder

app/volumecontrol.js
=> Fix some lint errors

app/plugins/audio_interface/alsa_controller/index.js
Do not update mixer if output device is set Loopback by a plugin
This PR contains only the mod, no reformating
=> alsa_controller update index.js

test/volume_controller.js
Follow up to #1962
This isn't a real test that is run with `mocha` at this stage, but more a helper script to test `amixer` volume parsing. 
Has a few options, 
- Run directly on the device in question, 
-- Pass in which mixer to test 
-- Read the device's config file and try directly from that 
- Or just parse a sample amixer output. 
```
volumio@volumio:/volumio/test$ node volume_controller.js
:::Input:::
From String
Simple mixer control 'SoftMaster',0
Capabilities: volume
Playback channels: Front Left - Front Right
Capture channels: Front Left - Front Right
Limits: 0 - 99
Front Left: 10 [10%]
Front Right: 10 [10%]
:::Output:::
{ volume: 10, mute: false }
Testing on Device
Parsing config file config.json
:::Input:::
{ device: 1, mixer: SoftMaster}
:::amixer:::
Simple mixer control …
```
=> Tweak volume_controller test script

app/plugins/music_service/mpd/index.js
=> Bugfix date metainfo not pushed

app/plugins/system_controller/i2s_dacs/dacs.json
Signed-off-by: AMuszkat <ariel.muszkat@gmail.com>
=> add support for MERUS(TM) Amp piHAT ZW in dacs json file

utils/addlangstring.js
Should also sort the new English key..
=> [utils] Also sort `string_en` when inserting a new key

app/statemachine.js
Fixes issues:
- https://github.com/volumio/streaming-services/issues/63
- https://github.com/volumio/streaming-services/issues/59
=> Fixing consume issue

app/plugins/audio_interface/upnp/startUpnp.js, app/plugins/audio_interface/upnp/stopUpnp.js, app/plugins/miscellanea/albumart/serverStartup.js, app/plugins/system_controller/system/index.js, app/plugins/system_controller/volumio_command_line_client/commands/devmode.sh, app/plugins/system_controller/volumio_command_line_client/commands/pull.sh, app/plugins/system_controller/volumio_command_line_client/volumio.sh, index.js, pluginhelper.js, utils/hooks/pre-commit
Cleaned up some legacy paths and fixed `devmode` to work again.
Test with `volumio pull -b V/dev/buster https://github.com/ashthespy/Volumio2`
=> Buster tweaks

app/plugins/music_service/mpd/index.js
Hi, here a fix for play an album or artist from genre not working.
=> fix: play from genre not working

app/plugins/audio_interface/alsa_controller/index.js, app/volumecontrol.js
More robust handling of multi-device cards, especially in relation to mixers and volume
=> Proper handling of multidevice cards when using aplay to discover devices

app/i18n/strings_en.json
Adding translation keys used by volumio cloud for TIDAL and QOBUZ.
=> Added Volumio Cloud strings

app/i18n/strings_en.json, app/pluginmanager.js, app/plugins/user_interface/websocket/index.js, package.json, pluginhelper.js
Perform an `npm` style check using `engines` to determine whether a plugin can run on the current Volumio
=> Plugin dependency check

app/plugins/miscellanea/appearance/index.js, app/plugins/music_service/mpd/index.js, app/plugins/system_controller/i2s_dacs/index.js, app/plugins/system_controller/network/index.js, app/plugins/system_controller/networkfs/index.js, app/plugins/system_controller/system/index.js, app/plugins/system_controller/volumio_command_line_client/index.js
This set of commits improves the startup correctness of the core volumio plugins so that they properly complete asynchronous startup in `onVolumioStart` before progressing into `onStart`.
=> Startup correctness and performance

app/pluginmanager.js
Report enabled for enabled MyVolumio plugins
Return the plugin folder for MyVolumio plugins
=> Update the plugin manager to better handle MyVolumio plugins

utils/tests/checkRemoteEndpoints.js
=> Adding browsing performer url

app/index.js, app/plugins/system_controller/volumiodiscovery/index.js, app/plugins/user_interface/websocket/index.js
Reconnect socketio on ungraceful shutdown.
=> Added message to get audio outputs from foreign devices. 

app/i18n/strings_en.json, app/pluginmanager.js, app/plugins/user_interface/websocket/index.js, pluginhelper.js
Get, install and publish plugins for buster
=> Buster plugins
