index.js

If the user hit reload/refresh while using volumio, he may get an error in the browser about the non-existent pathname. With this he will be redirected to Volumio main page.
This entry is cosmetic and can be removed at any time if it impacts functionality.

Redirect to root if a pathname is used

---

app/plugins/user_interfaces/mpdemulation/index.js

Hi Volumio 2 team. I am an experienced developer who is also an audiophile. 
I use Volumio 1 on a raspberry Pi with my Almarro A340 valve monoblocks and a Chord 2Qute DAC. It works very well in a high-end system :-)
I am on the volumjo forums as piercer and am having difficulty getting set up for development. I do not have a spare Pi and so am trying to get development working on a VM following the instructions on GitHub without any success :-(
Anyway, I really want to help on this project - it combines 2 of my great passions.
Sp by way of introduction here is a small change to the InterfaceMPD. Large switch statements are inefficient and can be difficult to maintain. Therefore in this pull request I suggest using a command->handler map instead.
It also fixes one possible bug 
I think …

Migrating switch to map

---

app/plugins/music_services/airplay_emulation/index.js

The airplay emulation plugin now start shairport in a slight different way:
- first read shairport configuration template and replace parameters with runtime values (such as device name and audio port)
- then start shairport via airplay systemd, "restart" is used to ensure clean start
TODO here: at the moment the audio also port is hard coded "hw:1,0" but it can be easily changed when runtime configuration will supply this value

Airplay emulation plugin

---

app/plugins/system_controllers/networkfs/index.js

According to #166 Size is now the total size for files and not the size of the mounted volume

Mounts : Size calculation 

---

app/plugins/audio_interfaces/alsa_controller/index.js
app/plugins/music_services/mpd/index.js

**Functionality**
When searching through the sound card directory (/proc/asound/) the sound card numbers no longer need to be sequential. All cards with directories of the form card(\d+) and id files inside will be made available as Alsa cards.
The Audio device names are shown in a human readable form - coming from the card<>/id file instead of the card<>/pcm0p/infor file. this means instead of multiple 'USB Audio' entries in the UI you can actually see what USB audio device is being referred to.
After saving the new output device in the UI the mpd.conf file is updated.
After saving the new mpd.conf file an attempt is made to restart mpd and use the new config.
**File Permissions**
In the current distribution of volumio the mpd.conf file is read-write for user:mpd and read-only for …

Alsa Output Control From the UI

---

app/playqueue.js
app/plugins/user_interfaces/websocket/index.js

I noticed that in CorePlayQueue constructor there was a promise created for the play queue which is immediately resolved. 
```
var self = this;
self.commandRouter = commandRouter;
self.stateMachine = stateMachine;
self.queueReadyDeferred = libQ.defer();
self.queueReady = self.queueReadyDeferred.promise;
self.arrayQueue = [];
self.queueReadyDeferred.resolve();
```
This promise was then returned every time that the play queue was accessed (adding, removing items and retrieving).
The add and remove items in particular wrapped another promise in this pre-resolved promise
```
return self.queueReady
.then(function() {
self.arrayQueue.splice(nIndex, 1);
return self.commandRouter.volumioPushQueue(self.arrayQueue);
});
```
This seems entirely unnecessary.
I have removed this pre-resolved promise …

Play Queue Simplification?

---

app/plugins/system_controllers/volumiodiscovery/index.js

Please not the config.json value "service" (AKA serviceName in the volumiodiscovery plugin) is used as a template for name capitalisation. so if "service" is "vOlumio" you'll have device names "vOlumio", "vOlumio-2", "vOlumio-3" and so on. If the name is changed by user, no capitalisation is done (unless the name give by the user contain the serviceName. For example if the user call it aGoodvolumio, it may be changed to aGoodvOlumio during subsequent reboots.

capital letters are preserved, using serviceName when possible

---

app/plugins/music_services/mpd/index.js

i.e. Display 125:04:08 instead of 125:4:8

Display leading 0 for single digit minutes and seconds of Playtime

---

app/plugins/system_controllers/i2s_dacs/dacs.json

add ST400 dac (pcm5122) - amp : http://www.audiophonics.fr/en/raspberry-pi/st-400-hat-module-class-d-amp-headphone-amp-dac-pcm5122-24bit192khz-p-10248.html

add ST400 DAC - Amp board

---

app/plugins/system_controllers/networkfs/index.js

contrary to `rm -rf`, `rmdir` only deletes empty directories, which should be what we're dealing with after a successful unmount.
See also #524

use rmdir instead of rm -rf to remove mountpoint

---

app/plugins/system_controller/i2s_dacs/dacs.json

Remove "digital" mixer for hifiberry dac because it has not mixer control.

remove mixer "digital" for hifiberry-dac

---

app/plugins/system_controller/network/index.js

Hostapd will ignore 'empty' lines or those beginning with '#'.
A line with a single space is not treated as 'empty', hostapd tries to
interpret it and gives an error. So replace it with a comment line that
explains the situation.

Fix syntax in hostapd*.conf if hotspot is disabled in volumio settings.

---

app/plugins/system_controller/volumio_command_line_client/commands/playback.js

I added the missing header line in [playback.js](https://github.com/volumio/Volumio2/blob/master/app/plugins/system_controller/volumio_command_line_client/commands/playback.js), wich prevented commands like `volumio next` from working.

Added missing Shebang line

---

app/plugins/system_controller/networkfs/index.js

Without the COMMON. prefix, the ILLEGAL_CHARACTER_/ warning is not displayed
by the warning popup.

Fix undisplayed warning

---

app/i18n/strings_ca.json
app/i18n/strings_da.json
app/i18n/strings_de.json
app/i18n/strings_en.json
app/i18n/strings_es.json
app/i18n/strings_fi.json
app/i18n/strings_fr.json
app/i18n/strings_it.json
app/i18n/strings_ja.json
app/i18n/strings_nl.json
app/i18n/strings_pl.json
app/i18n/strings_pt.json
app/i18n/strings_sv.json
app/i18n/strings_zh.json
app/plugins/system_controller/networkfs/index.js

If the user fails to type anything in the 'Alias' field of
network-drives-add-edit-drive.html then addShare fails with the following
somewhat obscure error in the logs:
Missing error handler on `socket`.
TypeError: Cannot read property 'indexOf' of undefined
and no indication to the user of what the problem is (particularly if this
is their first attempt to add a network drive).
In addition, the share is not mounted.
Fix by making sure 'name' is always defined and raising a warning in the webui
when 'name' is empty or all-spaces. To get a displayable warning I had to copy NETWORKFS.ALIAS_DOC from the webui into the string list.

Handle undefined or 'blank' share alias

---

app/volumecontrol.js

I was able to reproduce this easily and the obvious fix seems to work. Not tested with a DAC, just onboard analog out.

Don't allow volume to be stepped below zero. Fixes #857

---

app/plugins/miscellanea/albumart/albumart.js

Make it clear the error is related to albumart, and log the infoPath
that caused the problem. This change was triggered by trying to understand
where messages like
ERRORE: Got error: The artist you supplied could not be found
were coming from.

Improve the message logged when albumart lookup fails

---

README.md

I removed some unticked points of the todo list: 
-- [ ] Spotify Integration
-- [ ] Common queue for Music Library and Spotify Integration
-Both tasks are under development on [playqueue branch](https://github.com/volumio/Volumio2/tree/playqueue)
=> it's mentioned it was for RC2...  you confirm I can remove it?
See also #863

Update readme: link to doc and remove duplicated/outdated info

---

app/plugins/system_controller/network/index.js

to be consistent with https://github.com/volumio/Build/pull/114
BTW it very much seems hostapd.tmpl in build  (https://github.com/macmpi/Build/blob/master/scripts/volumioconfig.sh#L419) does not serve much purpose.

add driver=nl80211 in hostapd.conf

---

app/plugins/system_controller/i2s_dacs/index.js
app/statemachine.js

This fix takes care of the case when Repeat mode is on by adding two new conditional statements in the method CoreStateMachine.prototype.increasePlaybackTimer:
1.) It checks if the current track is the last track of the queue then the next track is set to the first track in the prefetch phase, unless Consume mode is on.
2.) At the end of the current track, if that track is the last track it sets the current track to the first track unless Consume mode is on.
If the consume mode also is on the last track has to be consumed. No need for next track.
It has been tested also with the other modes. Remember that Random and Consume override Repeat in MPD.
Repeat + Random = Random;  
Repeat + Consume = Consume; 
Random + Repeat + Consume should be Repeat + Consume, but this combination is still …

Fixes Repeat mode in the State Machine module

---

app/plugins/system_controller/i2s_dacs/dacs.json

This change adds current Pimoroni DAC products: pHAT DAC, Speaker pHAT and Picade HAT.
All three use the HiFiBerry DAC overlay, however Speaker pHAT will require some further work to enable support for the built-in VU Meter.

Added pHAT DAC, Speaker pHAT and Picade HAT

---

app/plugins/system_controller/networkfs/index.js

Issue #684 revealed that linux-mountutils, which we use for mounting NAS drives,
does not handle mountpoints with spaces in them very well - it fails to take
into account the octal encoding of some characters in /etc/mtab (details in
getmntent(7)). This can lead to failures to create mountpoints and failures
to detect that a given share is mounted.
Change how the mountpoint path is constructed from the share name - replace any
characters that get encoded with an underscore. Use this method consistently
in all functions that have to mount or unmount a share. 
This has been tested by adding, editing and deleting an NFS share with a        
space in the name/alias. This also will conflict with earlier pull requests;
please pull this first, I will rework the other changes once this is merged. …

Avoid unsuitable characters in mountpoints

---

app/index.js

Not all translations are complete, so we can't rely on i18nStrings having
even the top level of the language strings. To avoid crashing with a TypeError,
check the first element of a two-element template exists before trying to
check the second element exists.
Fixes: #992

Avoid referencing undefined elements in i18nStrings array

---

app/plugins/system_controller/networkfs/index.js

This series addresses some aspects of a few reports (#341, #432, #524, #684)
where a share was deleted in the MyMusic UI but not properly unmounted.
The changes have all been tested on 2.041 + PR#1010.

Deleteshare fixes

---

app/plugins/system_controller/networkfs/index.js

It seems best to just silently fix the mistake than bother the user with popups (that would have to be translated).

mount.cifs fails if given '//server//path'; so clean up the input path 

---

app/plugins/music_service/last_100/index.js

Tested against 2.118, by  ```chmod 000 /data/laststates.json```. 
Before these changes, volumio crashes on trying to read and things get really weird if one plays a track while the state file unwriteable.
After, it does not crash and the last_100 list is updated (only tested going from 1 to 2 songs). 
The user gets no feedback that something is amiss, but that's a different issue.
This should fix #941 but could stand testing with a full last_100 list.

Fix crashes in last_100

---

app/plugins/system_controller/networkfs/index.js

After tweaking the mountpoint paths a while ago, I started looking at strange paths on the remote share. After trying all sorts of quoting & escaping schemes I realised the problem was in linux-mountutils.
I've tested this with a few different strangely-named samba shares and tested mountpoints with things like () and ' in them, for CIFS and NFS. More testing would be welcome. Existing shares _should_ continue to work, as these changes don't affect how the mountpoint string is constructed.
The patch to linux-mountutils has been sent upstream but might have to be carried for a while.

More robust mounting

---

app/plugins/system_controller/networkfs/index.js

This is cleanup, no functional changes. The focus is on making the way fields accessed with config.get() is consistent across functions within the module.
Tested on 2.118 + linux-mountutils-1.02 + the 'more robust mounting' patch. Add/edit/delete of shares seemed to work ok.

Working with share configuration objects

---

app/plugins/system_controller/i2s_dacs/dacs.json

Adding pisound (http://blokas.io/pisound) to volumio.
Note that the latest pisound module code is available in 4.4.41 RPI kernel version.
Also I found that if switching from dac with 'needsreboot=yes' to 'needsreboot=no', reboot should still happen, without it, the output doesn't work.

Adding pisound to dacs.json

---

app/pluginmanager.js
http/index.js

The issue referenced below reports the upload stops part way through. This is because the wget command falls over:
```
Mar 22 11:25:35 volumio volumio[3248]: Uploading: auto_play(1).zip
Mar 22 11:25:35 volumio volumio[3248]: Upload Finished of auto_play(1).zip
Mar 22 11:25:36 volumio volumio[3248]: info: Downloading plugin at http://127.0.0.1:3000/plugin-ser
ve/auto_play(1).zip
Mar 22 11:25:36 volumio volumio[3248]: info: Cannot download file http://127.0.0.1:3000/plugin-serv
e/auto_play(1).zip - Error: Command failed: /usr/bin/wget -O /tmp/downloaded_plugin.zip http://127.
0.0.1:3000/plugin-serve/auto_play(1).zip
Mar 22 11:25:36 volumio volumio[3248]: /bin/sh: 1: Syntax error: "(" unexpected
Mar 22 11:25:36 volumio volumio[3248]: info: Error: Error: Error: Command failed: /usr/bin/wget …
```

Avoid  upload failures on certain filenames

---

app/plugins/music_service/mpd/index.js

The bug arose from a NaN on UI (issue #1099) while playing a file with 32bit floating point bit depth

Fixed MPD status samplerate:bits:channels when bits=f

---

app/plugins/system_controller/system/devices.json
app/plugins/system_controller/volumio_command_line_client/commands/kernelsource.sh

Preparation for newer kernel support while ensuring full backward compatibility.
**cpuinfo Hardware** returned chipset families (BCM2708/09/10) before kernel 4.8.y, and returns SoC reference (BCM2835/6/7) since then.

Pi Models detection compatibility

---

app/index.js
app/pluginmanager.js

add 2 methods **onVolumioReboot** and **onVolumioShutdown** for **pluginManager**. These methods call respectively **onVolumioReboot** and **onVolumioShutdown** on every enabled plugins.
Update the CoreCommandRouter reboot and shutdown methods, calling the pluginManager.onVolumioReboot  or pluginManager.onVolumioShutdown just before the real reboot or shutdown

add pre-end-of-life actions mechanism on plugins

---

app/plugins/miscellanea/appearance/index.js
app/plugins/system_controller/my_volumio/index.js

Adding `return libQ.resolve();` in `onVolumioStart()` for _appereance_ and _myvolumio_ plugins.

missing onVolumioStart return libQ.resolve();

---

app/plugins/system_controller/network/index.js

Use /etc/resolv.conf.head instead of /etc/resolv.conf.tail
As per https://github.com/volumio/Volumio2/issues/1031
Still need to fix:
- UI logic rework (critical)
------ ON/OFF should activate or clear the .head file (or move in/out with other name), and restart network
------ SAVE should should not do anything to the file if OFF
- UI display to show current DNS server used by /etc/resolv.conf

Fixing Manual DNS entry

---

app/plugins/music_service/mpd/index.js

Fill Artist with name if Artist is undefined. This enables nicer parsing of radio stations for LCD's.
It allows the user to show the radio station in addition to any info streamed from the station (e.g. the currently playing track).

Fill Artist with name if Artist is undefined

---

app/plugins/music_service/airplay_emulation/index.js

I looked at the code and thought that can't possibly be right...the mixer never gets into the config file.
The only test I have made is uploading the modified file (to v2.129) and checking that volumio restarts cleanly and that /etc/shairport-sync.conf looks sane after being updated. I don't know how to test it further.
On my system the config file contains no mixer:
```
general =
{
name = "Volumio";
log_verbosity = 0;
};
alsa =
{
output_device = "plughw:0,0";
};
sessioncontrol =
{
run_this_before_play_begins = "/usr/bin/mpc stop";
allow_session_interruption = "yes";
};
```

Ensure mixer gets updated in shairport-sync.conf

---

app/plugins/system_controller/i2s_dacs/index.js

`writeI2SDAC` and `disableI2SDAC` rewrote `config.txt` entirely, which caused issues if users or plugins purposely modified `config.txt`.
Proposed changes let `i2c_dacs` plugin only modify the necessary i2s `dtparam` for DACs.

i2c_dacs plugin: just modify config.txt, no full rewrite

---

app/asd.sh
app/plugins/system_controller/volumio_command_line_client/commands/kernelsource.sh
app/plugins/system_controller/volumio_command_line_client/volumio.sh

The traditional bourne shell (sh) does not support the 'function foo { ... }'
syntax, use the POSIX standard syntax, 'foo() { ... }', to improve portability.
The later syntax works with bash, sh and many other standard shells.
Fixes issue #904.

volumio_command_line_client: Use POSIX syntax for functions

---

app/pluginmanager.js
package.json

plugin install eventually does some quite intensive file I/O operations for deflating and moving directories around.
This PR replaces `decompress-zip` by native `miniunzip` and use linux `mv` operations.
Installs are now much faster, but more importantly much more RAM efficient.
`/tmp` is only used for first download, deflating happens in storage location, hence saving RAM (intermediate files are cleaned as soon as possible too).
Notes:
- `decompress-zip` can be removed from Volumio2 modules (not used elsewhere)
- `minizip` must be added to Build as per [relevant PR](https://github.com/volumio/Build/pull/207) (used `minizip` as `unzip` is overflowing `stdout`)
fixes https://github.com/volumio/Volumio2/issues/1220

Optimize plugin install/update

---

app/pluginmanager.js

This PR just focuses on improving promise management in load/start/stop plugins operations.
It fixes the infrastructure, so that later PR may further enhance load-order priorities management, make startup-sequence more deterministic, etc...
It does benefit right-now to add-on plugin Start/Stop operations which are more reliable.
Some important note:
- all plugins `onVolumioStart()` must now return promises and will crash if not.
Built-in plugins now comply with that, but some 3rd Party plugins may not. I contacted most plugins developers and submitted relevant PRs in [volumio-plugins](https://github.com/volumio/volumio-plugins/pulls): it should be ok when eventually merged. We may want to add a note into plugin [development docs about …

Pluginmanager: improve load, start, stop promise management

---

pluginhelper.js

Pre-existing package may not have new version number set at publish time: therefore, previously generated zip file may contain `package.json` with out-of-sync version number...
So it is safer to always re-create archive during publish.
Note: `zip()` already takes care of overwriting eventual older package, so no need to wipe before.

pluginhelper: always compress within Publish

---

pluginhelper.js

Volumio does not include `zip` utility by default, so compress fails (unless added extra).
Since `minizip` is readily available, we use it instead.

pluginhelper: fix compress

---

app/plugins/system_controller/system/index.js
logsubmit.js

@pilifsch found, to his/her confusion, that logsubmit does silly things when given a description containing parentheses. This series improves the quoting of the data from the /dev form so that should no longer happen.
Tested on stock 2.201 with just these changes.

Improve user input hygiene in logsubmit.js

---

app/index.js

Currently the GUI changes the start button in a pause button when playing local files, but changes it to a stop button when playing webradio, as webradio cannot be paused succesfully. This is correct.
The problem is with remote controls. A remote control without a dedicated stop button has its play/pause button mapped to execute 'volumio toggle'. In case of webradio this would pause the stream, which would put the player in a wrong state. Firstly, the stream cannot not be started again using the remote ('volumio toggle' stops working), and secondly, the button in the GUI does not change, i.e. in the GUI it looks like the stream is still playing.
This fix changes 'volumio toggle' to check if webradio is playing and issue a stop() instead of the normal pause(). The code is equivalent to the …

'volumio toggle' fix for webradio

---

pluginhelper.js

`cp` command keeps a copy of plugin archive within source directory: at next submit this zip file will be part of commit in source directory, which is not desirable (plugin archive is submitted elsewhere).
We could do this differently (by having zip function always produce file in `/tmp` for instance), but this works and does not affect anything else.

pluginhelper: move package.zip out of source directory

---

app/plugins/miscellanea/alarm-clock/index.js

It's easy to spot a sleep being enabled, (```Set Sleep at ...```), less so for one being disabled, because setSleep is called, usually with a nonzero timeout.
Tested on 2.201, rpi2.

Make it clearer in the log when a sleep has been disabled

---

app/plugins/system_controller/volumio_command_line_client/commands/pull.sh
app/plugins/system_controller/volumio_command_line_client/volumio.sh

Add a feature to volumio pull command to be able to specify branch and forked github repository for easier testing.
`volumio pull` Pulls latest github status on **_master_** from _https://github.com/volumio/Volumio2.git_
`volumio pull -b <branch>`  Pulls branch **_branch_** from _https://github.com/volumio/Volumio2.git_
`volumio pull -b <branch> <repository>`  Pulls branch **_branch_** from git repository **_repository_**
You can choose if this feature makes sense to you.

Volumio pull feature for branch and forked repository

---

app/plugins/system_controller/system/index.js
http/dev/dev.js
logsubmit.js

The fix I submitted a few days ago did not handle an important case - single quotes in the description. I've fixed that now, in the same way as we did in networkfs. The fix has been tested, see eg pBwpQAT.
While I was there I noticed the catch() clauses were using what seemed to be the wrong name for the error object.
Finally as described in #1237 I found it may be useful to clean up the data sent to socket.on('pushSendBugReport` before trying to parse it into json.
Comments and further testing welcome. Tested on 2.201 plus these patches.

More logsubmit work

---

app/randomqueue.js

Hello,
I am thrilled that Volumio now have a real shuffle mode thanks to abrarmahmood's contribution. Elegant code. Well done! Thanks.
So I tested it as once I had 2.246 up and working. At least for me Shuffle works only once, when I start to play a track again after the playlist is done the first time it only plays one track. When I combine Shuffle and Repeat some tracks seem not be played at all.
In this pull request I think i have fixed those two minor issues. It works for me. Check it out.
Details:
a) In the original code this.position that acts as a kind of shuffle counter is not reset after shuffle is done. I added a conditional statement in next and previous for that.
b) When Shuffle and Repeat is combined I changed when this.position is reset (when the next value of this.position …

Some small tweaks for Shuffle

---

logsubmit.js

Another place for passwords to lurk was reported. 
Tested with 2.246 on rpi2. That turned up another oversight, that the backslashes in the sed  backreferences needed to be doubled in order to survive the various quotings as we construct the string that gets ```execSync()```ed.
To add to the fun, the ```<elided>``` string ends up being invisible when viewing the htmlified log in a browser window, but can be revealed by 'view source'. We wanted to hide that text anyway, so no further change needed.
Please test...

Logsubmit3

---

app/plugins/system_controller/volumio_command_line_client/volumio.sh

While we're there, name the other commands controlling the volumio service consistently.
I couldn't find any internal commands using these but perhaps this is an API break.
Fixes #1427. Not tested beyond making sure 'volumio vstop' doesn't fail with 'command not found'.

Make 'volumio vstop' work

---

app/plugins/music_service/mpd/index.js

Fixes these issues:
volumio/Volumio2/[#1458](https://github.com/volumio/Volumio2/issues/1458)
volumio/Volumio2/[#1453](https://github.com/volumio/Volumio2/issues/1453)
volumio/Volumio2/[#1441](https://github.com/volumio/Volumio2/issues/1441)  [Likely fix, not 100% sure]
For people who's collections have no orphaned tracks (tracks without an album), these changes should make no difference.
@volumio 
Hey Michealangelo
I know you're super busy. If you can find the time I'd appreciate you taking a quick look at my two PRs and providing feedback. There is a bit more I'd like to contribute (sorting and performance related), but that all builds on top of the two PRs I've already made, so I'd first need to know if they actually make any sense and can be accepted into the master repo before I …

Improved handling of orphaned tracks

---

app/plugins/music_service/webradio/index.js

Some uris in the dirble search results contain end of line characters,
which break things downstream in volumio. Stripping them away makes things
work again.
This addresses #1484. Lightly tested against 2.362 (rpi2).

Ensure clean uris from Dirble

---

app/plugins/system_controller/system/index.js
app/plugins/system_controller/volumio_command_line_client/volumio.sh
logsubmit.js

This adds support for
```
$ volumio logdump
```
which will save a logsubmit.js report to local storage, for the times when networking is broken.
Also, save the log when the upload fails, so it can be transmitted by other means.
Getting this to work required setting PATH in volumio.sh, for reasons explained in 'Make the PATH that is in use unambiguous'.
Tested on 2.346.

Save logsubmit logs locally

---

pluginhelper.js

Save some SD card space, especially given the growing number of plugins! 
I doubt everyone need the entire commit history on their Volumio instance ;-)
```bash
git clone https://github.com/volumio/volumio-plugins.git
Cloning into 'volumio-plugins'...
remote: Counting objects: 12279, done.
remote: Compressing objects: 100% (114/114), done.
remote: Total 12279 (delta 24), reused 128 (delta 20), pack-reused 12139
Receiving objects: 100% (12279/12279), 159.75 MiB | 5.22 MiB/s, done.
Resolving deltas: 100% (4671/4671), done.
Checking connectivity... done.
Checking out files: 100% (4625/4625), done.
```
```bash
$ git clone https://github.com/volumio/volumio-plugins.git --depth 5 --no-single-branch
Cloning into 'volumio-plugins'...
remote: Counting objects: 4075, done.
remote: Compressing …
```

pluginhelper: Use shallow clone

---

app/plugins/audio_interface/alsa_controller/cards.json

Currently experimental only.
The Intel SST and HDMI/DP LPE Audio devices need to be treated a little different.
bytcr-rt5651 needs a default mixer and HDMI is on hw:2,0, currently not clear what hw:0,0 and hw:1,0 are meant for (Analogue out and Display Port)?

First Intel Atom Baytrail/ Cherrytrail sound support

---

pluginhelper.js

Instead of creating the websocket connection at startup for each
invokation, do it only within the 2 methods that currently require
one: `install` and `update`.
This has the nice side effect of not preventing the script to exit
properly when calling any of the other commands, like `refresh`.
Additionally, the use of `process.exit()` is discouraged, and it's better
to just set an `exitCode` so that any unprocessed event in the event loop
will be handled before exiting.
See here https://nodejs.org/api/process.html#process_process_exit_code
for more details.

Don't create a websocket inconditionally at startup

---

app/plugins/miscellanea/albumart/albumart.js
app/plugins/miscellanea/albumart/index.js
app/plugins/music_service/mpd/index.js
app/plugins/music_service/upnp_browser/index.js
app/plugins/music_service/webradio/index.js
package.json

Further to my [nodev8 upgrade findings](https://github.com/volumio/Build/issues/315) , I see that even the [prebuild node `v8.11.0` modules from the repo](http://repo.volumio.org/Volumio2/node_modules_arm-8.11.0.tar.gz) throws up :
```shell
$ npm list --depth=0
+-- nodetools@0.0.1 invalid
npm ERR! invalid: nodetools@0.0.1 /volumio/node_modules/nodetools
```
There are some fs-extra issues as well, but that is for another day ;=)
`nodetools` package - do we really need it? 
Current usage: 
```shell
$ git grep nodetools
app/plugins/miscellanea/albumart/albumart.js:var nodetools = require('nodetools');
app/plugins/miscellanea/albumart/albumart.js:            var decodedArtist=nodetools.urlDecode(artist);
app/plugins/miscellanea/albumart/albumart.js:            var …
```

Remove redundant `nodetools` package dependency

---

app/plugins/system_controller/i2s_dacs/dacs.json

Support Adafruit MAX98357 I2S Class-D Mono Amp
for Raspberry Pi. For more details and wiring
instructions visit:
https://learn.adafruit.com/adafruit-max98357-i2s-class-d-mono-amp/
Signed-off-by: Leon Anavi <leon@anavi.org>

dacs.json: Add Adafruit MAX98357

---

app/plugins/system_controller/networkfs/index.js

NFS mounts require an absolute path to the exported directory on the server.
The volumio UI does not encourage this, as the default is mouting via CIFS.
To avoid troubling the user with these details, fix up the path before the
configuration is used or saved to disk.
Motivation: volumio/Volumio2-UI#511.

Enforce leading / on NFS path supplied by user

---

app/statemachine.js

Fixes prefetching too many times due timer overrunning when buffering track & makes sure prefetchDone variable is always reset when the timer is reset to prevent unwanted behavior when queue has 2 consecutive tracks from different music services.
Full explanation in forum: https://volumio.org/forum/bugs-statemachine-increaseplaybacktimer-method-t10340.html

Fix timer overrun bug & prefetchDone not reset bug

---

package.json

Given that we are using just the formatting function for now.
Once format_fix is merged, and everyone is on board, we can enable it again, gently nudging people to actually fix the lint errors ;-) 
So workflow for the interim would be:
```shell
git add <file0.js> <file1.js>
npm run lint-staged
git commit -m 'Formatted files ready with my new commit'
```

[codestyle] Disable git-hooks until full repo is linted

---

.travis.yml

Travis is still using Node 6.1.0 to run tests (or actually, the only
test we have so far).
Bump the version to make sure it matches the one used in the live system.

Use the right node version for Travis

---

app/plugins/system_controller/volumio_command_line_client/volumio.sh

The pull command is supposed to support the ability to pull a
specific branch, either from the official Volumio repo or from a
custom repo.
Is seems like this was either not working or a regression has been
introduced at some point.
This commit fixes the behaviour by passing to the pull.sh script
all the parameters passed to the pull() funciton in volumio.sh.

Pass all the arguments to pull.sh

---

app/index.js

Not sure if this matters but it's inconsistent which just wastes mental bandwidth. Every other call is readJsonSync().
Tested(?) on 2.513 by switching language to DE.

There is no readJSONSync() function

---

app/plugins/music_service/mpd/index.js

- When a `browseLibrary` request is received, exclude folders beginning with `.` from the array that's returned to the client.
- Folders hidden with `.` are hidden system folders and are normally not available to the user. These include directories like `.Trashes` that can easily be included on the user's media drive without them being aware of it. It's very strange to see these displayed to the user. Here's an example:
- The solution is crude and inelegant, but the surrounding code in `mpd/index.js` is not the easiest to work with, so I went with something very simple that won't require any refactoring to implement.

fix: exclude hidden folders from directory browsing

---

app/plugins/audio_interface/alsa_controller/index.js

Currently `alsa.outputdevicemixer` returns an `undefined` when Mixer type is set to `None`.

Fix `undefined` mixer when mixer type is None

---

app/plugins/music_service/mpd/index.js

**Scenario**: 
In Music Library Settings: _Show Track Numbers_ is **enabled** and a file doesn't have tracknumber metadata. The resulting entry in the music browser displays as a single hyphen "-". The filename does come through correctly when _Show Track Numbers_ is off.
The crux of the code is this snippet, which is laced through several of the MPD music service methods:
```
if (!tracknumbers) {
var title = self.searchFor(lines, i + 1, 'Title:');
}
else {
var title1 = self.searchFor(lines, i + 1, 'Title:');
var track = self.searchFor(lines, i + 1, 'Track:');
var title = track + " - " + title1;
}
... // a few lines later...
// Subsequently the title will be either the composite title from above, or 'name' which is the filename.
if (title) {
title = title;
} else {
title = name;
}
```
The …

Fix track title display in music browser when tracknumber metadata doesn't exist

---

app/pluginmanager.js

Some plugins in MyVolumio will require access to the main config
file for plugins. Pass it over to MyVolumioPluginManager when
creating a new instance.

Pass a reference to config file to MyVolumio

---

app/pluginmanager.js
app/plugins/miscellanea/my_music/index.js

Instead of relying on any core plugin, in this case the `my_music` plugin, to know which plugins / services in MyVolumio require a special treatment, delegate the possibility to pull in additional UIConfig elements to the PluginManager code, which in turns will delegate it to MyVolumio's own PluginManager.

Encapsulate all the logic for MyVolumio plugins in the PluginManager

---

app/playqueue.js

It seems at least possible some data can be fed to this function that doesn't contain the 'uri' field.
Otherwise, why the check when calling ```self.commandRouter.logger.info``` ?

Check 'uri' field is defined before using

---

app/plugins/user_interface/websocket/index.js

Create new getPlaylistContent API for websocket. Used as:
`io.emit('getPlaylistContent', {name:"Playlist Name"});`
Returns:
```
pushPlaylistContent:{
name: 'playlist name',
lists: [
[ { ... }, { ... } ]
]
}
```

Add getPlaylistContent to websockets

---

app/pluginmanager.js

Use the correct variable name when printing the error

Use the correct variable

---

app/i18n/strings_de.json
app/i18n/strings_en.json
app/plugins/miscellanea/my_music/UIConfig.json

Headline for Sources has been changed from "MY_MUSIC" to "SOURCES". A translation string has been added accordingly for english and german.

Changed sources headline and added translation string

---

app/plugins/music_service/webradio/index.js

Another function, listRadioFavourites(), uses the same message
("Cannot list Favourites") which makes it difficult to distinguish
the source of an error if one occurs.

Make error message distinct

---

app/plugins/audio_interface/alsa_controller/index.js

Use of 'this' looks inconsistent with the rest of the function but may be ok, I'll leave that up to you.
Tested on 2.692 pi. I don't have a hardware mixer but that shouldn't matter.
I was unable to get any debug-level log output from anywhere in volumio, so perhaps I'm missing something here.
Discovered while looking into #1832 .

Selflogger

---

app/plugins/audio_interface/alsa_controller/index.js

With 'self' not defined, the self.checkValidMixer condition is always false
and no mixers get added to the mixers array.
Fixes: #1832
Tested on a rpi with no Dac, no explosions.
Testing on an rpi with a Dac should be done soon - done, seems to fix the issue.

Ensure checkValidMixer actually gets called

---

app/statemachine.js

This PR fix next / prev functions while playing webradio !
I tested the modifications suggested in this post below and the next / prev functions work correctly!
https://github.com/volumio/Volumio2/issues/1122
To fix the problem a first modification is necessary in 
Volumio2-UI/src/app/services/player.service.js
```
@@ -69,15 +69,11 @@ class PlayerService {
}
prev() {
-    if (this.state.trackType !== 'webradio') {
this.socketService.emit('prev');
-    }
}
next() {
-   if (this.state.trackType !== 'webradio') {
this.socketService.emit('next');
-    }
}
skipBackwards() {
```
Changes must be coupled with another from main volumio2-UI in 
Volumio2-UI/src/app/services/player.service.js
PR link : [volumio/Volumio2-UI/pull/711]
hoping it will be useful !

Fix next / prev functions while playing webradio (2/2)

---

app/plugins/audio_interface/alsa_controller/index.js

Picking up from #1890, I've refactored `getAplayInfo()` to use regex to parse the card `id`, `name` and `device`, keeping the rest of the logic the same. Tested it on a few(two) boards, and seems to do the job. 
Some questions though:
1. Should `getAplayInfo()` also return `devices`?
1. Is there a reason why `namesArray` is needed? Are `TinkerAudio OnBoard` and `USB Audio OnBoard` devices on the same card?

Refactor and simplify `getAplayInfo` to be more robust

---

app/plugins/system_controller/i2s_dacs/dacs.json

There is syntax error in `i2s_dacs/dacs.json` that will prevent the Volumio service from starting..
771710b (#1888) Introduces a syntax error (one pesky comma!)..
```
/volumio/node_modules/fs-extra/node_modules/jsonfile/index.js:73
throw err
^
SyntaxError: /volumio/app/plugins/system_controller/i2s_dacs/dacs.json: Unexpected token ] in JSON at position 9071
at JSON.parse (<anonymous>)
at Object.readFileSync (/volumio/node_modules/fs-extra/node_modules/jsonfile/index.js:69:17)
at ControllerI2s.eepromDetect (/volumio/app/plugins/system_controller/i2s_dacs/index.js:176:19)
at ControllerI2s.i2sDetect (/volumio/app/plugins/system_controller/i2s_dacs/index.js:146:24)
```
Took the opportunity to fix other minor whitespace issues as well..

Fix syntax error in `dacs.json`

---

app/plugins/music_service/webradio/index.js

Play queue items contain a valid .name field but not necessarily
a valid .title field. One instance where this happens when a webradio
is saved to a playlist and the playlist is added to the play queue.
Check .title is defined before overwriting the .name field.
Otherwise, the item will be shown in the queue with a name of "undefined".
This is an alternative fix to the approach in #1816.
Tested on 2.657 for these cases:
- webradio saved as a playlist and playlist added to queue (shows as 'undefined' in playqueue before patch)
- webradio from 'my web radios' added to the playqueue
- webradio from 'volumio selection' added to the playqueue
- single track from an album in music library added to the playqueue

Check before overwriting .name field of a queue item.

---

app/index.js
index.js

We should have a way to keep track/time certain events, to gain insight into the system. As we add new features this becomes vital for user experience, and moreover gives the devs an idea on where to focus to improve things. 
Ideally, this data should also exposed to the `/dev` page and/or ultimately into the `downloader-v1` remote api. 
Not sure if this is the best way to do this, but it's a start (and requires no external dependencies..) 
I am also aware that given the async nature plugin manager, this doesn't represent true boot times - but that is a different matter..

Simple bench/metrics framework to time events

---

app/plugins/audio_interface/alsa_controller/cards.json

Limit playback device to mixed I2S+HDMI+SPDIF for Khadas VIM1 and VIM2 until mainline kernel

Khadas AML-MESONAUDIO: limit to first mixed device

---

package.json

This was breaking new builds, as it used everywhere, but listed as a dev dependency only.

Add missing `fs-extra` package to dependencies

---

app/index.js

As we already log to console. 
Use `journalctl -o cat -u volumio.service` if required instead..

Remove dedicated logging to `/var/log/volumio.log`

---

app/volumecontrol.js

I seem to have introduced issues with the software mixer with dd3f21a, sorry!
This is just fixing the symptoms, as I believe the linting has unearthed the real error which was just being silently ignored.
The error comes from [these comparisons](https://github.com/volumio/Volumio2/commit/dd3f21a6e5152129a7355e3f40e57728accc614c#diff-b98fabba6904d236aaed2fa990bc5281L324-R334):
```diff
case 'mute':
// Mute
self.getVolume(function (err, vol) {
-            if (vol == null) {
+            if (err) {
+              self.logger.error('Cannot get ALSA Volume: ' + err);
+            }
+            if (vol === null) {
```
The problem was that `vol` was never `null` when the parsing failed, but instead was `undefined`. 
Thus `undefined == null => true` but `undefined === null => false`  
**Now this …

Fix regression with volumecontroller 

---

test/volume_controller.js

Follow up to #1961
We could refactor `getInfo` to use a single Regex and handle more cases. 
As a first step, here is a simple testing framework.  A good idea would be to collect multiple typical inputs, and also some edge cases.  Once we are happy with the regex, can refactor `getInfo` to use it.
```shell
volumio@volumio:/volumio$ node ./test/volume_controller.js
:::Input:::
Simple mixer control 'SoftMaster',0
Capabilities: volume
Playback channels: Front Left - Front Right
Capture channels: Front Left - Front Right
Limits: 0 - 99
Front Left: 10 [10%]
Front Right: 10 [10%]
mute:  undefined
{ volume: 10, mute: false }
:::Input:::
Simple mixer control 'PCM',0
Capabilities: pvolume pswitch pswitch-joined
Playback channels: Front Left - Front Right
Limits: Playback 0 - 110
Mono:
Front Left: …
```

Add a simple test for ALSA volume parsing Regex

---

app/plugins/system_controller/system/index.js
http/dev/dev.js
http/dev/views/index.ejs

Added a way to tail logs (via `journalctl -f`) to the dev page. This should make it easier for non console people to quickly get info that helps with debugging. There is a bit of overlap b/w this and the submit a log feature, but this can also help users debug stuff quickly. 
There is no max limit on the number of lines, but considering this is client side, should be fine?
Looks something like this:

Add an entry in the dev page to tail logs

---

app/plugins/system_controller/i2s_dacs/dacs.json

Note: drivers are still being mainlined - it should not effect other functionality even if the drivers aren’t mainlined yet.
Compiled binaries for most recent kernel are already available, they could be integrated in build script.
Driver have been already included in experimental Buster build

adding BassOwl-HAT to DAC list

---

app/plugins/system_controller/i2s_dacs/dacs.json

These are our high end soundcards - will add budget soundcards later.
Isolated requires kernel after 17th June 2020, e.g. kernel 5.4.58 or an 
equivalent 4.19.xx kernel. 5.4.58 or later is preferred.
https://github.com/Hexxeh/rpi-firmware/commit/23141000a5eae7ddbe11d4ac283198afd3031263

Adds support for the AudioInjector.net Isolated & Ultra 2 soundcards.

---

package.json
utils/addlangstring.js

Makes adding new language strings a bit simpler - it adds the given string to the default (English) file  and empty strings to the rest of the languages.
```shell
npm run addLangString -- ALARM TEST 'This is my test string'
npm run addLangString -- COMMON MY_SETTING 'This is my setting string'
npm run addLangString -- COMMON MY_SETTING_DESC 'This is my setting description string'
```
It has very rudimentary error handling, so ensure the files are checked in so you can `git checkout .\app\i18n\*.json` to recover from mishaps..

Add a language string helper util

---

pluginhelper.js

Should slim down `node_modules` for plugin that use `devDependencies`

[pluginhelper] Add `--production` flag to npm install

---

app/plugins/system_controller/volumio_command_line_client/volumio.sh
update-helper.js

I want to update my 4 volumio hosts in parallel via an Ansible playbook, but due to the nature and current implementation of the update script, I can not update in headless mode.
This PR forwards all arguments passed to the shell script to the node update script and checks for the `--yes` or `-y` flag in `forceupdate` to skip the y/n prompt and just perform the update.
As an extra I also fixed the shell script and quoted variables which could otherwise get expanded if they contained a space. More info: https://github.com/koalaman/shellcheck/wiki/SC2068

Add functionality to perform headless updates

---

app/plugins/user_interface/rest_api/index.js

Sending back an empty arrary string is better than sending an error string in the body of the response. 
When writing a client application, one assumes that a string array of URLs will be sent as a response. If instead a custom message is sent as a response when no URLs have been entered, this message must be handled separately in the client, which is extremely unpleasant.

Send empty array if no urls are defined

---

app/plugins/audio_interface/alsa_controller/cards.json

The buster/master branch is missing the latest commits to the master branch. This one is needed for testing MP1

Fix soundcard name for MP1, leaving VIM1/VIM2/VIM3 as is

---

app/index.js

Must be a change in Node.JS to make fs.writeFile more picky about input...

Prevent volume slider from springing back

---

app/plugins/system_controller/i2s_dacs/index.js

This is unnecessary now that we use the alsa card name instead of the card number to keep track, and syncrhonise the config on volumio start

Remove the special case for moving Raspberry Pi I2S DAC numbers

---

app/volumecontrol.js

Was a `String`, should be a `Number` as per rest of the code in this module..

Fix `Volume.vol` type when parsing Software mixer

---

app/plugins/system_controller/system/index.js

Set the system player name correctly when it is changed, rather than always regardless of what config value is being set

System player name configuration

---

app/plugins/system_controller/networkfs/index.js
app/plugins/system_controller/system/index.js

This commit will prevent the Volumio mount handler breaking the installtodisk process for x86 as soon as a partptobe is done in a situation where the target device did not previously hold a Volumio partition scheme.
The new  `disableDeviceActions` and `enableDeviceActions` in the networkfs plugin can also be used in other situations where mounting external partitions is to be temporarily suspended.

x86: installtodisk, prevent Volumio mount actions during process

---

app/plugins/music_service/webradio/index.js

When the info is available, codec and bitrates are displayed in radio browser. 
This is not always accurate and propagates the info from the used radio directories.

added codec and bitrate to radio stations in browse

---

app/plugins/audio_interface/alsa_controller/cards.json

Support for some old hardware, one with an ATI Graphics and an SB soundcard (both commonly used, therefore relevant).
User knows he needs to test this.

cards.json: support for older x86 ATI cards

---

app/index.js
app/statemachine.js

We should not check if value is greater than 0, since then we cant move first item in the queue.

Fix issue where moving first item of the queue is not possible

---

app/plugins/music_service/mpd/index.js

When parsing MPD's track info, the MPD plugin checks whether the stream URI contains the letters 'bbc'. If it does, it assumes the URI has got to be a BBC web radio stream. The plugin then proceeds to replace 'bbc' with 'BBC' in the `Name` property of the track info object. Now, while web radio streams will often have a `Name` tag, this is not always the case with other types of streams. With those streams that do not have a `Name` tag, parsing will fail resulting in Volumio not updating playback status nor proceeding to the next song after the current one finishes playing.
This PR fixes the issue by checking for the existence of the `Name` property in the track info object.

MPD plugin: Fix handling of URIs containing 'bbc'
